---
- name: Install
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: true

- name: Create
  ansible.builtin.file:
    path: "/var/www/{{ item }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'
  loop: "{{ sites }}"

- name: Deploy vhost
  ansible.builtin.template:
    src: vhost.conf.j2
    dest: "/etc/nginx/sites-available/{{ item }}.conf"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ sites }}"
  notify: restart nginx

- name: Enable
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/{{ item }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ item }}.conf"
    state: link
  loop: "{{ sites }}"

- name: Deploy index
  ansible.builtin.template:
    src: index.html.j2
    dest: "/var/www/{{ item }}/index.html"
    owner: www-data
    group: www-data
    mode: '0644'
  loop: "{{ sites }}"
